server:
  port: 8080
  error:
    include:
      message: true

spring:
  application:
    name: rangiffler-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

rangiffler-front:
  base-uri: 'http://127.0.0.1:3001'
